name: traccar_manager
description: "Traccar Manager"
publish_to: 'none'
version: 6.1.1+81

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^7.2.1
  firebase_analytics: ^12.6.0
  firebase_core: ^4.15.0
  firebase_crashlytics: ^5.4.0
  firebase_messaging: ^16.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.2.0-beta.3
  flutter_secure_storage: ^11.2.0
  http: ^1.6.0
  local_auth: ^3.0.2
  path_provider: ^2.1.6
  permission_handler: ^13.0.2
  rate_my_app: ^2.4.2
  share_plus: ^13.3.1
  shared_preferences: ^2.5.5
  shared_preferences_android: ^2.4.28
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
